apiVersion: apps/v1
kind: Deployment
metadata:
  name: user_managment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user_managment
      gateway: enabled
  template:
    metadata:
      labels:
        app: user_managment
    spec:
      containers:
        - name: user_managment
          image: auto-sans-risque/user_managment:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: user_managment
spec:
  selector:
    app: user_managment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
