version: '3'

services:
  gateway:
    image: dhouib/auto-sans-risque:_gateway
    ports:
      - "8000:8000"
    depends_on:
      - admin
      - communication
      - diagnosis
      - user_management

  admin:
    image: dhouib/auto-sans-risque:admin
    ports:
      - "8001:8001"
    env_file:
      - ./admin/.env


  communication:
    image: dhouib/auto-sans-risque:communication
    ports:
      - "8002:8002"
    env_file:
      - ./communication/.env


  diagnosis:
    image: dhouib/auto-sans-risque:diagnosis
    ports:
      - "8003:8003"
    env_file:
      - ./diagnosis/.env

  user_management:
    image: dhouib/auto-sans-risque:user_management
    ports:
      - "8004:8004"
    env_file:
      - ./user_management/.env

