POST http://localhost:3009/models
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A

{
  "name": "KIA"
}

###

POST http://localhost:3009/models/paginate
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A

{
  "withChoose": false,
  "filter": {},
  "pageNumber": 1,
  "pageSize": 2,
  "sortField": "default",
  "sortOrder": "desc"
}

###
PUT http://localhost:3009/models/617a95b86ac6b629a448f51a
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A

{
  "name": "Citroën"
}

###
DELETE  http://localhost:3009/models/617a90c87ba2ce11f4ee8a56
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A
