POST http://localhost:3009/expert
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A

{
  "name": "Renault"
  //"marks":["617a764db9a6583bec8d82e1"]
}

###

GET http://localhost:3009/expert/614d033bd48a45b853235207
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A

###
PUT http://localhost:3009/expert/614d033bd48a45b853235207
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A

{
  "specialitiesModels": [
    "617a95b86ac6b629a448f51a"
  ],
  "specialitiesMarks": [
    "617a95c96ac6b629a448f51b",
    "617a99fb6990d40e141180fc"
  ]
}

###
DELETE  http://localhost:3009/expert/617a90c87ba2ce11f4ee8a56
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A
