POST http://localhost:3009/auth/signup/moderator
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A

{
    "fullName":"moderator",
    "email":"moderator@gmail.com",
    "tel":"23581547",
    "allows":{
      "menus":{
        "dash":true,
        "clients":true,
        "experts":true,
        "rapports":true,
        "reclama":true,
        "assist":true,
        "missions":true,
        "avis":true
      },
      "configs":{
        "marks":true,
        "articles":true,
        "packs":true,
        "ads":true,
        "rapport":true
      }
    },
    "password":"123456",
    "roles":"MODERATOR"
}

###

Post http://localhost:3009/moderator/paginate
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A

{
  "filter":{},
  "pageNumber": 1,
  "pageSize": 3,
  "sortField": "default",
  "sortOrder": "asc"
}

###
GET http://localhost:3009/moderator/618e8c350651683dd8f91272
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A


###
PUT http://localhost:3009/moderator/61925851f591663ef00f4552
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A

{
    "fullName":"moderator",
    "tel":"21475447",
    "isVerified":false,
    "allows":{
      "menus":{
        "dash":true,
        "clients":false,
        "experts":true,
        "rapports":true,
        "reclama":true,
        "assist":true,
        "missions":true,
        "avis":true
      },
      "configs":{
        "marks":true,
        "articles":true,
        "packs":true,
        "ads":true,
        "rapport":true
      }
    }
}

###
DELETE  http://localhost:3009/moderator/61923bf3c193c71d1c9a1adb
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A

###
POST   http://localhost:3009/moderator/delete
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpLmtvdWJhYWFAZ21haWwudG4iLCJyb2xlIjpbXSwiaWF0IjoxNjMyNDcyMTAzLCJleHAiOjE2MzM3NjgxMDN9.iifDorbbFerLKd2LS_vpGoxf3yefyDm4U_ImnL3dh5A

{
  "ids":[
    "61923fcb60c43525f8c5659a"
  ]
}