FROM node:16 AS development

WORKDIR /usr/src/app

COPY --chown=node:node package.json yarn.lock ./

USER root

RUN apt-get update && apt-get install -y \
             chromium \
             openjdk-11-jre-headless \
             gconf-service \
             libasound2 \
             libatk1.0-0 \
             libatk-bridge2.0-0 \
             libc6 \
             libcairo2 \
             libcups2 \
             libdbus-1-3 \
             libexpat1 \
             libfontconfig1 \
             libgcc1 \
             libgconf-2-4 \
             libgdk-pixbuf2.0-0 \
             libglib2.0-0 \
             libgtk-3-0 \
             libnspr4 \
             libnss3 \
             libpango-1.0-0 \
             libpangocairo-1.0-0 \
             libstdc++6 \
             libx11-6 \
             libx11-xcb1 \
             libxcb1 \
             libxcomposite1 \
             libxcursor1 \
             libxdamage1 \
             libxext6 \
             libxfixes3 \
             libxi6 \
             libxrandr2 \
             libxrender1 \
             libxss1 \
             libxtst6 \
             ca-certificates \
             fonts-liberation \
             libappindicator1 \
             lsb-release \
             xdg-utils \
             wget && \
             yarn install --frozen-lockfile

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

COPY --chown=node:node . .

USER node

FROM node:16 AS build

WORKDIR /usr/src/app

COPY --chown=node:node package.json yarn.lock ./

COPY --chown=node:node --from=development /usr/src/app/node_modules ./node_modules

COPY --chown=node:node . .

RUN yarn build

USER node




FROM node:16 AS production

WORKDIR /usr/src/app

COPY --chown=node:node --from=build /usr/src/app/dist ./dist
COPY --chown=node:node --from=build /usr/src/app/package.json /usr/src/app/yarn.lock ./

ENV NODE_ENV production

RUN yarn install --production --frozen-lockfile && yarn cache clean

RUN apt-get update && apt-get install -y \
             chromium \
             openjdk-11-jre-headless \
             gconf-service \
             libasound2 \
             libatk1.0-0 \
             libatk-bridge2.0-0 \
             libc6 \
             libcairo2 \
             libcups2 \
             libdbus-1-3 \
             libexpat1 \
             libfontconfig1 \
             libgcc1 \
             libgconf-2-4 \
             libgdk-pixbuf2.0-0 \
             libglib2.0-0 \
             libgtk-3-0 \
             libnspr4 \
             libnss3 \
             libpango-1.0-0 \
             libpangocairo-1.0-0 \
             libstdc++6 \
             libx11-6 \
             libx11-xcb1 \
             libxcb1 \
             libxcomposite1 \
             libxcursor1 \
             libxdamage1 \
             libxext6 \
             libxfixes3 \
             libxi6 \
             libxrandr2 \
             libxrender1 \
             libxss1 \
             libxtst6 \
             ca-certificates \
             fonts-liberation \
             libappindicator1 \
             lsb-release \
             xdg-utils \
             wget

CMD [ "yarn", "start" ]
