# Stage 1: Development
FROM node:16 AS development

WORKDIR /usr/src/app

COPY --chown=node:node package*.json yarn.lock ./

RUN yarn install

COPY --chown=node:node . .

# Stage 2: Build
FROM development AS build

RUN yarn build

# Stage 3: Production
FROM node:16 AS production

WORKDIR /usr/src/app

COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
COPY --chown=node:node --from=build /usr/src/app/dist ./dist

ENV NODE_ENV production

RUN yarn install --production --frozen-lockfile && yarn cache clean

USER node

CMD [ "node", "dist/main.js" ]
