apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication
      gateway: enabled
  template:
    metadata:
      labels:
        app: communication
    spec:
      containers:
        - name: communication
          image: auto-sans-risque/communication:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: communication
spec:
  selector:
    app: communication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
