version: '0.1'

services:
  admin:
    image: dhouib/auto-sans-risque:admin
    ports:
      - 8001:8001
    env_file:
      - ./.env
    networks:
      - auto-sans-risque

networks:
  auto-sans-risque:
    external: true
