apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
      gateway: enabled
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: auto-sans-risque/admin:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
