name: Build and Push Docker Images

on:
  push:
    branches:
      - microservices

env:
  DOCKER_USERNAME: dhouib
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: auto-sans-risque

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ _gateway, admin, communication, diagnosis, user_management ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and Push Image
        run: |
          cd backend/${{ matrix.directory }}
          echo ${{ matrix.directory }}
          docker build -t $DOCKER_USERNAME/$DOCKER_REPO:${{ matrix.directory }} .
          docker push $DOCKER_USERNAME/$DOCKER_REPO:${{ matrix.directory }}
