name: Build and Push Docker Images

on:
  push:
    branches:
      - microservices

env:
  DOCKER_USERNAME: dhouib
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: auto-sans-risque

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ _gateway, communication, diagnosis, user_management ]

    steps:
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Image
        run: |
          cd backend/${{ matrix.directory }}
          echo ${{ matrix.directory }}
          docker build -t $DOCKER_USERNAME/$DOCKER_REPO:${{ matrix.directory }} .
          docker push $DOCKER_USERNAME/$DOCKER_REPO:${{ matrix.directory }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ client-side-main , admin-main ]

    steps:
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Image
        run: |
          cd ${{ matrix.directory }}
          echo ${{ matrix.directory }}
          docker build -t $DOCKER_USERNAME/$DOCKER_REPO:${{ matrix.directory }} .
          docker push $DOCKER_USERNAME/$DOCKER_REPO:${{ matrix.directory }}

  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: [ build-and-push-backend, build-and-push-frontend ]
    env:
      VPS_IP: 149.202.50.65
      SSH_USER: ubuntu
      SSH_PASSWORD: DfspT4ND42aQ
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: Connect to VPS and Deploy
        env:
          SSH_USER: your_ssh_user
        run: |
          sshpass -p $"SSH_PASSWORD" ssh $SSH_USER@${VPS_IP} 'cd /home/auto-sans-risque-docker && docker-compose pull && docker-compose up -d'

      - name: Clean up unnecessary images
        env:
          SSH_USER: your_ssh_user
        run: |
          sshpass -p $"SSH_PASSWORD" ssh $SSH_USER@${VPS_IP} 'docker image prune -af'