name: Build and Push Docker Images

on:
  push:
    branches:
      - microservices

env:
  DOCKER_USERNAME: dhouib
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: auto-sans-risque

jobs:
  docker-connect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and Push Images
        run: |
          ls 
          cd backend
          for dir in _gateway admin communication diagnosis user_management; do
            cd $dir
            echo $dir
            docker build -t $DOCKER_USERNAME/$DOCKER_REPO:$dir .
            docker push $DOCKER_USERNAME/$DOCKER_REPO:$dir
            cd ..
          done
