name: Build and Push Docker Images

on:
  push:
    branches:
      - microservices

env:
  DOCKER_USERNAME: dhouib
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: auto-sans-risque

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  build-and-push-backend:
    runs-on: ubuntu-latest
    needs: docker-login
    strategy:
      matrix:
        directory: [ _gateway, communication, diagnosis, user_management ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Image
        run: |
          cd backend/${{ matrix.directory }}
          echo ${{ matrix.directory }}
          docker build -t $DOCKER_USERNAME/$DOCKER_REPO:${{ matrix.directory }} .
          docker push $DOCKER_USERNAME/$DOCKER_REPO:${{ matrix.directory }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    needs: docker-login
    strategy:
      matrix:
        directory: [ client-side-main ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Image
        run: |
          cd ${{ matrix.directory }}
          echo ${{ matrix.directory }}
          docker build -t $DOCKER_USERNAME/$DOCKER_REPO:${{ matrix.directory }} .
          docker push $DOCKER_USERNAME/$DOCKER_REPO:${{ matrix.directory }}
